/**
 * Daily photo prompts — one line per day of year (index 0 = Jan 1).
 * Feel free to edit or extend.
 */
window.MEMORY_JAM_PROMPTS = [
  "Something that made you smile today",
  "Your morning drink or breakfast",
  "A texture you like (fabric, wood, stone…)",
  "The sky right now",
  "Your feet or your shoes",
  "A plant — real or fake",
  "Something red",
  "Your shadow",
  "A book, screen, or page you're reading",
  "Something borrowed or shared",
  "Water — glass, tap, rain, or puddle",
  "A corner of your home that feels safe",
  "Something with stripes or dots",
  "Food that is your comfort",
  "A door or a window",
  "Something handmade",
  "Your hands doing something",
  "A sound you could photograph (show the source)",
  "Something blue",
  "A gift or a package",
  "Street or path under your feet",
  "Something that sparkles or reflects",
  "Your workspace or study spot",
  "A pet or a creature (or a toy stand-in)",
  "Something you would save in a fire (metaphor ok)",
  "Light through a curtain or blind",
  "A snack mid-day",
  "Something green",
  "Clock or time-telling object",
  "Your mug or cup collection (one counts)",
  "Something soft",
  "Art on a wall or fridge",
  "Something cold or warm to the touch",
  "A tool you used today",
  "Something with writing on it",
  "Your bag or pocket contents (safe to share)",
  "Something orange or yellow",
  "A face — yours in a mirror is fine",
  "Something broken or repaired",
  "Music — show the speaker, vinyl, or app",
  "Something purple or pink",
  "Your bed or blanket",
  "Something metal",
  "A sign or label that caught your eye",
  "Something round",
  "Your dinner plate",
  "Something tiny",
  "Something huge (or the biggest thing nearby)",
  "A pattern you noticed",
  "Something that smells good (show it)",
  "Something nostalgic",
  "Something new to you",
  "Something old",
  "A color combo you love",
  "Something in motion (blur allowed)",
  "Something perfectly still",
  "Your favorite chair",
  "Something with a face (not human ok)",
  "A stack of things",
  "Something transparent or glassy",
  "Something fuzzy",
  "Your keys or wallet",
  "Something you fixed or cleaned",
  "A reflection — mirror, phone, or puddle",
  "Something spicy or sweet (the thing, not the taste)",
  "Something from outside brought in",
  "Something you almost threw away",
  "A label with a funny name",
  "Something cozy",
  "Something sharp or pointy (careful)",
  "Something smooth",
  "Something rough",
  "Something that reminds you of a person",
  "Something that reminds you of a place",
  "Your shoes again — different angle",
  "Something with numbers",
  "Something with stripes today",
  "Something edible growing",
  "Something packaged",
  "Something unwrapped",
  "A lamp or light source",
  "Darkness with one bright spot",
  "Something ceramic",
  "Something plastic you like anyway",
  "Something wooden",
  "Something stone or concrete",
  "Something fabric — clothes or cloth",
  "Something that makes noise when moved",
  "Something silent",
  "Something expensive-feeling",
  "Something free",
  "Something found on the ground",
  "Something on a shelf",
  "Something in a drawer (safe)",
  "Something seasonal",
  "Something out of season",
  "Something with a story you could tell",
  "Something you want to remember",
  "Your jar (or the idea of it) — meta photo",
  "Something that feels like home",
  "Something that feels like adventure",
  "Something small enough for a pocket",
  "Something too big to carry",
  "A texture opposite of yesterday",
  "Something symmetrical",
  "Something messy on purpose",
  "Something neat and tidy",
  "Something with more than three colors",
  "Something monochrome",
  "Something that fits in one hand",
  "Something that needs two hands",
  "Something you will not need tomorrow",
  "Something you will need tomorrow",
  "Something that surprised you",
  "Something ordinary made interesting",
  "Something beautiful in bad light",
  "Something ugly you still like",
  "Something borrowed from nature",
  "Something purely human-made",
  "Something that rhymes with your mood",
  "Something that does not match anything else",
  "Something with a sticker",
  "Something with peeling paint",
  "Something brand new",
  "Something vintage",
  "Something you would put in a time capsule",
  "Something you would not show anyone — abstract it",
  "Something that feels like a hug",
  "Something that feels like a sprint",
  "Something quiet",
  "Something loud (show the culprit)",
  "Something wet",
  "Something dry",
  "Something hot",
  "Something cold",
  "Something spicy-looking",
  "Something sweet-looking",
  "Something bitter — coffee counts",
  "Something sour — citrus counts",
  "Something umami — show it",
  "Something from a window view",
  "Something from floor level",
  "Something from above (careful)",
  "Something in a bag",
  "Something out of the bag",
  "Something with a cord or cable",
  "Something wireless",
  "Something analog",
  "Something digital",
  "Something printed",
  "Something handwritten",
  "Something typed",
  "Something stitched",
  "Something glued",
  "Something taped",
  "Something nailed",
  "Something floating",
  "Something sinking",
  "Something flying (or about to)",
  "Something crawling",
  "Something still life — arrange it",
  "Something candid — no posing",
  "Something posed — embrace the cheese",
  "Something blurry on purpose",
  "Something tack sharp",
  "Something overexposed",
  "Something underexposed",
  "Something silhouetted",
  "Something backlit",
  "Something front-lit",
  "Something side-lit",
  "Something with bokeh",
  "Something with deep focus",
  "Something minimal",
  "Something maximal",
  "Something empty",
  "Something full",
  "Something half-full (optimist)",
  "Something half-empty (honest)",
  "Something with a face drawn on",
  "Something with a real face",
  "Something with no face at all",
  "Something that could be a postcard",
  "Something that could be album art",
  "Something that could be a meme",
  "Something serious",
  "Something silly",
  "Something peaceful",
  "Something chaotic",
  "Something orderly",
  "Something wild",
  "Something tame",
  "Something domestic",
  "Something wild — literal or vibe",
  "Something local",
  "Something imported",
  "Something homemade",
  "Something store-bought you love",
  "Something you would gift",
  "Something you would keep",
  "Something you would share",
  "Something only you understand",
  "Something everyone would get",
  "Something mysterious",
  "Something obvious",
  "Something subtle",
  "Something loud visually",
  "Something quiet visually",
  "Something high contrast",
  "Something low contrast",
  "Something neon",
  "Something pastel",
  "Something earth tone",
  "Something jewel tone",
  "Something metallic",
  "Something matte",
  "Something glossy",
  "Something dusty",
  "Something polished",
  "Something rough-cut",
  "Something precise",
  "Something improvised",
  "Something planned",
  "Something accidental",
  "Something intentional",
  "Something lucky",
  "Something unlucky that turned out ok",
  "Something that needs explaining",
  "Something self-explanatory",
  "Something from childhood",
  "Something for your future self",
  "Something for a friend",
  "Something for yourself",
  "Something you almost forgot",
  "Something you will never forget",
  "Something that fits the word 'jam'",
  "Something that fits the word 'memory'",
  "Something that fits the word 'cozy'",
  "Something that fits the word 'pixel'",
  "Something that fits the word 'life'",
  "Your favorite photo from this month — retake the vibe",
  "Anything — today is a wild card",
  "Anything — wild card again",
  "Anything — last wild card of the quarter",
  "Something tiny in a big frame",
  "Something big in a tight crop",
  "Something that looks like food but is not",
  "Something that is food and looks like art",
  "Something with crumbs",
  "Something spotless",
  "Something lived-in",
  "Something staged",
  "Something candid of an object",
  "Something that looks like a painting",
  "Something that looks like a photo of a photo",
  "Something meta",
  "Something sincere",
  "Something ironic",
  "Something earnest",
  "Something playful",
  "Something serious again",
  "Something that makes you laugh",
  "Something that makes you pause",
  "Something that makes you grateful",
  "Something that makes you curious",
  "Something that answers a question",
  "Something that asks a question",
  "Something open",
  "Something closed",
  "Something locked",
  "Something unlocked",
  "Something with a key",
  "Something with a lock",
  "Something safe",
  "Something risky — stay safe",
  "Something wholesome",
  "Something edgy — stay kind",
  "Something soft light",
  "Something harsh light",
  "Something golden hour",
  "Something blue hour",
  "Something noon-bright",
  "Something night-quiet",
  "Something rainy",
  "Something sunny",
  "Something foggy",
  "Something clear",
  "Something windy — show evidence",
  "Something still air",
  "Something hot drink",
  "Something cold drink",
  "Something shared drink",
  "Something solo drink",
  "Something celebratory",
  "Something mundane celebrated",
  "Something ritual",
  "Something spontaneous",
  "Something repeated daily",
  "Something once-only",
  "Something you want to repeat",
  "Something you want to remember exactly as-is",
  "Something you are ok forgetting — photo it first",
  "Something that feels like this app",
  "Something that is not like anything else — your pick",
];
